export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_BUY_REQUEST = 'PRODUCT_BUY_REQUEST';
export const PRODUCT_BUY_SUCCESS = 'PRODUCT_BUY_SUCCESS';
export const PRODUCT_BUY_FAIL = 'PRODUCT_BUY_FAIL';

export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';

export const PRODUCT_USER_REQUEST = 'PRODUCT_USER_REQUEST';
export const PRODUCT_USER_SUCCESS = 'PRODUCT_USER_SUCCESS';
export const PRODUCT_USER_FAIL = 'PRODUCT_USER_FAIL';

export const PRODUCT_HISTORY_REQUEST = 'PRODUCT_HISTORY_REQUEST';
export const PRODUCT_HISTORY_SUCCESS = 'PRODUCT_HISTORY_SUCCESS';
export const PRODUCT_HISTORY_FAIL = 'PRODUCT_HISTORY_FAIL';